# -*- coding: utf-8 -*-
"""AluraStoreLatam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-vuVuU9qgxJVQZKCmsCKisoPdlbOR2B-

### Importación de datos
"""

import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_1%20.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science-latam/refs/heads/main/base-de-datos-challenge1-latam/tienda_4.csv"

tienda = pd.read_csv(url)
tienda2 = pd.read_csv(url2)
tienda3 = pd.read_csv(url3)
tienda4 = pd.read_csv(url4)

tienda.head()

"""#1. Análisis de facturación


"""

tienda.info()

ingresos_totales = tienda['Precio'].sum()
ingresos_totales2 = tienda2['Precio'].sum()
ingresos_totales3 = tienda3['Precio'].sum()
ingresos_totales4 = tienda4['Precio'].sum()

print(f'Ingresos totales para la primera tienda: {ingresos_totales}')
print(f'Ingresos totales para la segunda tienda: {ingresos_totales2}')
print(f'Ingresos totales para la tercera tienda: {ingresos_totales3}')
print(f'Ingresos totales para la cuarta tienda:  {ingresos_totales4}')

print('La primera tienda tiene mayor cantidad de ingresos')

"""# 2. Ventas por categoría"""

tienda_categoria = tienda['Categoría del Producto'].value_counts()
tienda2_categoria = tienda2['Categoría del Producto'].value_counts()
tienda3_categoria = tienda3['Categoría del Producto'].value_counts()
tienda4_categoria = tienda4['Categoría del Producto'].value_counts()

print(f'Ventas por categoria de la primera tienda:\n{tienda_categoria}')
print(f'Ventas por categoria segunda tienda:\n{tienda2_categoria}')
print(f'Ventas por categoria tercera tienda:\n{tienda3_categoria}')
print(f'Ventas por categoria cuarta tienda:\n{tienda4_categoria}')

"""# 3. Calificación promedio de la tienda

"""

calificacion_tienda = float(tienda['Calificación'].mean())
calificacion_tienda2 = float(tienda2['Calificación'].mean())
calificacion_tienda3 = float(tienda3['Calificación'].mean())
calificacion_tienda4 = float(tienda4['Calificación'].mean())

print(f'La calificacion promedio de los usuarios para la primera tienda es :{calificacion_tienda:.2f}')
print(f'La calificacion promedio de los usuarios para la segunda tienda es :{calificacion_tienda2:.2f}')
print(f'La calificacion promedio de los usuarios para la tercera tienda es :{calificacion_tienda3:.2f}')
print(f'La calificacion promedio de los usuarios para la cuarta tienda es :{calificacion_tienda4:.2f}')

"""# 4. Productos más y menos vendidos"""

max_tienda = tienda['Producto'].value_counts().idxmax()
max_tienda2 = tienda2['Producto'].value_counts().idxmax()
max_tienda3 = tienda3['Producto'].value_counts().idxmax()
max_tienda4 = tienda4['Producto'].value_counts().idxmax()

min_tienda = tienda['Producto'].value_counts().idxmin()
min_tienda2 = tienda2['Producto'].value_counts().idxmin()
min_tienda3 = tienda3['Producto'].value_counts().idxmin()
min_tienda4 = tienda4['Producto'].value_counts().idxmin()

print(f'El producto mas vendido de la primera tienda fue el {max_tienda} y el menos vendido fue {min_tienda}.')
print(f'El producto mas vendido de la segunda tienda fue {max_tienda2} y el menos vendido fue {min_tienda2}.')
print(f'El producto mas vendido en la tercera tienda fue {max_tienda3} y el menos vendido fue {min_tienda3}.')
print(f'El producto mas vendido en la cuarta tienda fue {max_tienda4} y el menos vendido fue {min_tienda4}.')

"""# 5. Envío promedio por tienda"""

costenvio_tienda = tienda['Costo de envío'].mean()
constenvio_tienda2 = tienda2['Costo de envío'].mean()
costenvio_tienda3 = tienda3['Costo de envío'].mean()
costenvio_tienda4 = tienda4['Costo de envío'].mean()

print(f'costo de envio promedio de la primera tienda :{costenvio_tienda:.3f}')
print(f'costo de envio promedio de la segunda tienda :{constenvio_tienda2:.3f}')
print(f'costo de envio promedio de la tercera tienda :{costenvio_tienda3:.3f}')
print(f'costo de envio promedio de la cuarta tienda :{costenvio_tienda4:.3f}')

print('El cliente de la primera tienda paga mas por el envio del producto, y el que menos paga por envio es en el de la cuarta tienda')

"""# 5. Generando Grafico"""

import matplotlib.pyplot as plt

fig, axs = plt.subplots(2, 2, figsize=(14,10))

ventas1 = tienda['Categoría del Producto'].value_counts()
ventas1.plot(kind='bar', ax=axs[0,0])
axs[0,0].set_title('Tienda 1')
axs[0,0].set_xlabel('Categoría')
axs[0,0].set_ylabel('Cantidad')

# Tienda 2
ventas2 = tienda2['Categoría del Producto'].value_counts()
ventas2.plot(kind='bar', ax=axs[0,1])
axs[0,1].set_title('Tienda 2')

# Tienda 3
ventas3 = tienda3['Categoría del Producto'].value_counts()
ventas3.plot(kind='bar', ax=axs[1,0])
axs[1,0].set_title('Tienda 3')

# Tienda 4
ventas4 = tienda4['Categoría del Producto'].value_counts()
ventas4.plot(kind='bar', ax=axs[1,1])
axs[1,1].set_title('Tienda 4')

plt.tight_layout()
plt.show()

tiendas = ['tienda 1', 'tienda 2', 'tienda 3', 'tienda 4']
ingresos = [ingresos_totales, ingresos_totales2, ingresos_totales3, ingresos_totales4]
plt.figure(figsize=(8,5))
plt.plot(tiendas, ingresos)
plt.xlabel('Tiendas')
plt.ylabel('Ingresos')
plt.title('Ingresos por Tienda')
plt.show()

calificacion = [calificacion_tienda, calificacion_tienda2,calificacion_tienda3, calificacion_tienda4]

plt.figure(figsize=(8,5))
plt.scatter(tiendas, calificacion)
plt.xlabel('Tiendas')
plt.ylabel('Calificacion')
plt.title('Calificacion por Tienda')

precios = [tienda['Precio'],tienda2['Precio'],tienda3['Precio'],tienda4['Precio']]

plt.figure(figsize=(8,5))
plt.boxplot(precios, tick_labels=['Tienda 1', 'Tienda 2', 'Tienda 3', 'Tienda 4'])
plt.xlabel('Tiendas')
plt.ylabel('Precio')
plt.title('Comparación de precios por tienda')
plt.show()

costo = [costenvio_tienda,constenvio_tienda2,costenvio_tienda3,costenvio_tienda4]
plt.figure(figsize=(8,5))
plt.barh(tiendas, costo)
plt.xlabel('costo de envio')
plt.ylabel('tiendas')
plt.title('Costo de envío vs Calificación')
plt.show()

t1 = tienda['Cantidad de cuotas'].mean()
t2 = tienda2['Cantidad de cuotas'].mean()
t3 = tienda3['Cantidad de cuotas'].mean()
t4 = tienda4['Cantidad de cuotas'].mean()

cuotas = [t1,t2,t3,t4]

plt.scatter(calificacion, cuotas)
plt.xlabel('Calificacion')
plt.ylabel('Cantidad de cuotas')
plt.title('Cantidad de cuotas por tienda')
plt.show()

plt.scatter(tiendas, cuotas)
plt.xlabel('Tienda')
plt.ylabel('Cantidad de cuotas')
plt.title('Cantidad de cuotas por tienda')
plt.show()

tienda2['Precio'].describe()

"""1. De acuerdo con los resultados obtenidos le recomendaria al señor Juan que vendiera la tienda 4, esta tienda es la que menos ingresos genera, ademas esta tienda no tiene una ventaja diferencial sobre las demas tiendas. La tienda 4 es la que menos cobra por envio, sin embargo esto no genera una mejor facturacion en cuanto a ingresos totales, esto demuestra que este factor de costo no ha sido suficiente para impulsar una mayor cantidad de ventas, es decir menor costo logistico no se traduce en una ventaja competitiva. Aunque esta tienda tiene buena calificacion con respecto a las tiendas 2 y 3 esta no genera la misma cantidas de ingresos.

#6. Analisis de desempeño Geografico
"""

!pip install folium

import folium
from folium.plugins import HeatMap

heat_data = tienda[['lat','lon']].values.tolist()

mapa_calor = folium.Map(
    location=[tienda['lat'].mean(), tienda['lon'].mean()],
    zoom_start=5
)

HeatMap(heat_data).add_to(mapa_calor)

mapa_calor

heat_data = tienda2[['lat','lon']].values.tolist()

mapa_calor = folium.Map(
    location=[tienda2['lat'].mean(), tienda2['lon'].mean()],
    zoom_start=5
)

HeatMap(heat_data).add_to(mapa_calor)

mapa_calor

heat_data = tienda3[['lat','lon']].values.tolist()

mapa_calor = folium.Map(
    location=[tienda3['lat'].mean(), tienda3['lon'].mean()],
    zoom_start=5
)

HeatMap(heat_data).add_to(mapa_calor)

mapa_calor

heat_data = tienda4[['lat','lon']].values.tolist()

mapa_calor = folium.Map(
    location=[tienda4['lat'].mean(), tienda4['lon'].mean()],
    zoom_start=5
)

HeatMap(heat_data).add_to(mapa_calor)

mapa_calor

electro_t1 = tienda[tienda['Calificación'] == 5]
ventas_t1 = electro_t1.groupby(['lat','lon']).size().reset_index(name='ventas')

lat_centro = tienda['lat'].mean()
lon_centro = tienda['lon'].mean()

mapa = folium.Map(
    location=[lat_centro, lon_centro],
    zoom_start=6
)

heat_data = ventas_t1[['lat','lon','ventas']].values.tolist()

HeatMap(
    heat_data,
    radius=12,
    blur=15,
    max_zoom=10
).add_to(mapa)

mapa

# Promedio de ingreso por coordenada
ingreso_geo = tienda.groupby(['lat','lon'])['Precio'].mean().reset_index()

plt.figure(figsize=(8,6))

scatter = plt.scatter(
    ingreso_geo['lon'],
    ingreso_geo['lat'],
    c=ingreso_geo['Precio'],
)

plt.colorbar(scatter, label='Ingreso Promedio')
plt.xlabel('Longitud')
plt.ylabel('Latitud')
plt.title('Ingreso Promedio por Ubicación')

plt.show()

lat_centro = tienda['lat'].mean()
lon_centro = tienda['lon'].mean()

mapa = folium.Map(
    location=[lat_centro, lon_centro],
    zoom_start=6
)

heat_data = ingreso_geo[['lat','lon','Precio']].values.tolist()

HeatMap(
    heat_data,
    radius=15,
    blur=20,
    max_zoom=10
).add_to(mapa)

mapa

ingreso_geo2 = tienda2.groupby(['lat','lon'])['Precio'].mean().reset_index()


lat_centro2 = tienda2['lat'].mean()
lon_centro2 = tienda2['lon'].mean()
mapa2 = folium.Map(location=[lat_centro2, lon_centro2],zoom_start=6)
heat_data2 = ingreso_geo2[['lat','lon','Precio']].values.tolist()
HeatMap(
    heat_data2,
    radius=15,
    blur=20,
    max_zoom=10
).add_to(mapa2)

mapa2

ingreso_geo3 = tienda3.groupby(['lat','lon'])['Precio'].mean().reset_index()
lat_centro3 = tienda3['lat'].mean()
lon_centro3 = tienda3['lon'].mean()

mapa3 = folium.Map(location=[lat_centro3, lon_centro3],zoom_start=6)
heat_data3 = ingreso_geo3[['lat','lon','Precio']].values.tolist()

HeatMap(
    heat_data3,
    radius=15,
    blur=20,
    max_zoom=10
).add_to(mapa3)

mapa3

ingreso_geo4 = tienda4.groupby(['lat','lon'])['Precio'].mean().reset_index()

lat_centro4 = tienda4['lat'].mean()
lon_centro4 = tienda4['lon'].mean()

mapa4 = folium.Map(location=[lat_centro4, lon_centro4],zoom_start=6)
heat_data4 = ingreso_geo4[['lat','lon','Precio']].values.tolist()

HeatMap(
    heat_data4,
    radius=15,
    blur=20,
    max_zoom=10
).add_to(mapa4)

mapa4

"""1. la tienda tiene mayor cantidad de ingresos entre el centro del pais, en ciudades como bogota, armenia, pereira y manizales, y en norte de santander en la ciudad de Cucuta, tambien tiene ingresos altos en la ciudad de villavicencio.

2. La tienda 2 tien mayor cantidad de ingresos en Bogota, armenia, pereira y manizales, y tambien una buena cantidad de ingresos es Inirida. las ventas mas bajas son en bucaramanga y leticia.

3. La tienda 3 tiene mayor cantidad de ingresos en la ciudad de manizales, valledupar, Bogota y soacha..

4. La Tienda 4 tiene mayor cantidad de ingresos en soachay menor numero de ingresos en inirida y leticia.

5. Laa 4 tiendas tienen la menor calificacion en bogota y medellin, se recomienda mejorar el servicio al cliente y la calidad de los productos en estas ciudades para aumentar la calidad del servicio ofrecido.

"""

